name: Build and Push Multi-Arch Docker Image

# Trigger only on pushes to main
on:
  push:
    branches:
      - main

# Ensure only one run per branch at a time
concurrency:
  group: build-and-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # PAT with write:packages

      # 3️⃣ Set up Docker Buildx for multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/gdudeunderscore/my-java-python-image:latest

      # 5️⃣ Optional: Verify Python installation
      - name: Verify Python installation
        run: docker run --rm ghcr.io/gdudeunderscore/my-java-python-image:latest python3 --version
