name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

# Only one workflow per branch at a time
concurrency:
  group: build-and-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Set up Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build and push multi-arch Docker image with caching
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/gdudeunderscore/my-java-python-image:latest
          cache-from: type=registry,ref=ghcr.io/gdudeunderscore/my-java-python-image:latest
          cache-to: type=registry,ref=ghcr.io/gdudeunderscore/my-java-python-image:latest,mode=max

      # 5️⃣ Optional: verify Python
      - name: Verify Python installation
        run: docker run --rm ghcr.io/gdudeunderscore/my-java-python-image:latest python3 --version
