name: Build and Push Multi-Arch Docker Image

# Trigger only on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # Make sure this PAT has write:packages

      # 3️⃣ Set up Docker Buildx for multi-arch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build and push Docker image (multi-platform)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/gdudeunderscore/my-java-python-image:latest

      # 5️⃣ Optional: Verify Python version in the image
      - name: Verify Python installation
        run: docker run --rm ghcr.io/gdudeunderscore/my-java-python-image:latest python3 --version
